#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ldacBT
Version  : 2.0.2.3
Release  : 2
URL      : https://github.com/EHfive/ldacBT/releases/download/v2.0.2.3/ldacBT-2.0.2.3.tar.gz
Source0  : https://github.com/EHfive/ldacBT/releases/download/v2.0.2.3/ldacBT-2.0.2.3.tar.gz
Summary  : LDAC Bluetooth ABR library.
Group    : Development/Tools
License  : Apache-2.0
Requires: ldacBT-license = %{version}-%{release}
Requires: ldacBT-plugins = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
# ldacBT
AOSP libldac dispatcher
https://android.googlesource.com/platform/external/libldac

%package dev
Summary: dev components for the ldacBT package.
Group: Development
Provides: ldacBT-devel = %{version}-%{release}

%description dev
dev components for the ldacBT package.


%package license
Summary: license components for the ldacBT package.
Group: Default

%description license
license components for the ldacBT package.


%package plugins
Summary: plugins components for the ldacBT package.
Group: Default

%description plugins
plugins components for the ldacBT package.


%prep
%setup -q -n ldacBT

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550354784
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1550354784
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ldacBT
cp LICENSE %{buildroot}/usr/share/package-licenses/ldacBT/LICENSE
cp libldac/LICENSE %{buildroot}/usr/share/package-licenses/ldacBT/libldac_LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ldac/ldacBT.h
/usr/include/ldac/ldacBT_abr.h
/usr/lib/libldacBT_abr.so
/usr/lib/libldacBT_enc.so
/usr/lib64/pkgconfig/ldacBT-abr.pc
/usr/lib64/pkgconfig/ldacBT-enc.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ldacBT/LICENSE
/usr/share/package-licenses/ldacBT/libldac_LICENSE

%files plugins
%defattr(-,root,root,-)
/usr/lib/libldacBT_abr.so.2
/usr/lib/libldacBT_abr.so.2.0.2.3
/usr/lib/libldacBT_enc.so.2
/usr/lib/libldacBT_enc.so.2.0.2.3
